function voteUp(id)
{
    document.getElementById(id).style.background="green";
}

function voteDown(id)
{
    document.getElementById(id).style.background="red";
}

window.onload = function() {

	var table = document.getElementById("tablePodemos");  	
	for (var i = 0; i < propuestasPodemos.length; ++i) {
		var row = table.insertRow(0);
		row.className = "propuesta cellStyle";
		id = "pod" + i;
		row.id = id;

		var cell1 = row.insertCell(0);
		var cell2 = row.insertCell(1);

		cell1.innerHTML = propuestasPodemos[i];
		cell1.className = "textoPropuesta";
		cell2.innerHTML = "<button onclick=\"voteUp('" + id + "')\">👍</button> &nbsp <button onclick=\"voteDown('" + id + "')\">👎</button></span>";
		cell2.className = "votos";
	}

	var table = document.getElementById("tableCiudadanos");  	
	for (var i = 0; i < propuestasCiudadanos.length; ++i) {
		var row = table.insertRow(0);
		row.className = "propuesta cellStyle";
		id = "ciud" + i;
		row.id = id;

		var cell1 = row.insertCell(0);
		var cell2 = row.insertCell(1);

		cell1.innerHTML = propuestasCiudadanos[i];
		cell1.className = "textoPropuesta";
		cell2.innerHTML = "<button onclick=\"voteUp('" + id + "')\">👍</button> &nbsp <button onclick=\"voteDown('" + id + "')\">👎</button></span>";
		cell2.className = "votos";
	}
};

var propuestasPodemos = [
	"Plan Nacional de Transición Energética",
	"Derogación del Real Decreto 900 / 2015, de 9 de octubre, y aprobación de una normativa que permita el desarrollo del autoconsumo eléctrico",
	"Impulso y desarrollo de infraestructuras verdes",
	"Adopción progresiva de una energía 100 % renovable en todas las dependencias de la Administración Pública",
	"Compromiso público de no autorizar instalaciones de fracking",
	"Realización de una auditoría de costes de todo el sistema eléctrico",
	"Modificación del marco regulatorio para que todas las fuentes de energía reciban una retribución razonable basada en los costes reales de producción",
	"Establecimiento de controles efectivos que impidan prácticas oligopólicas en el sistema eléctrico",
	"Protagonismo de las energías renovables en la planificación del sistema eléctrico",
	"Recuperación de las centrales hidroeléctricas por parte del Estado",
	"Garantía por ley del acceso a un suministro mínimo",
	"Diseño de una propuesta alternativa a la Estrategia Energética de la Comisión Europea",
	"Identificación de los costes de transición de la competencia",
	"Participación ciudadana y auditoría para la ejecución de grandes infraestructuras",
	"Las bicicletas como base de una movilidad urbana sostenible",
	"Garantía de acceso al transporte público",
	"Pacto Nacional por la Economía Productiva",
	"Apoyo a los clústeres para revertir el proceso de desindustrialización",
	"Aumento de la diversificación industrial y apuesta por el desarrollo de los servicios avanzados",
	"Creación de comités estratégicos sectoriales",
	"Impulso de una política industrial centrada en el desarrollo de competencias específicas",
	"Apuesta por las cláusulas sociales y la contratación pública como instrumentos de generación de valor social",
	"Puesta en marcha de fondos de inversión soberanos de carácter público",
	"Refuerzo de la competencia en sectores estratégicos",
	"Modernización de los servicios de las telecomunicaciones",
	"Reorientación de la inversión en infraestructuras públicas",
	"Desarrollo de la intermodalidad mediante la mejora de las conexiones ferroviarias de los puertos",
	"Reorientación del sector de la construcción",
	"Reparto de la renta agraria y adaptación de la normativa de los sectores agropecuario y pesquero",
	"Programa Nacional de Introducción a la Investigación",
	"Acercamiento de la ciencia a la sociedad: Centros de Innovación Ciudadana",
	"Redefinición de la carrera investigadora",
	"Portal online de investigación",
	"Apuesta por las investigadoras y los investigadores senior",
	"Garantía del acceso a la cultura científica",
	"Recuperación del talento joven: convocatoria Margarita Comas",
	"Pacto Estatal para la Ciencia y la Innovación",
	"Promoción de la actividad innovadora en el tejido empresarial",
	"Estímulo al retorno del talento científico emigrado",
	"Inversión en ciencia e I+D+i responsable",
	"Democratización de los OPIS",
	"Creación de un observatorio para la defensa de la transparencia en el acceso y gestión de las instituciones investigadoras y universitarias",
	"Investigación y docencia flexibles y autónomas",
	"Plan integral de lucha contra el fraude",
	"Ampliación a diez años del plazo de prescripción de los delitos fiscales",
	"Reforma del IRPF",
	"Recuperación del gravamen efectivo en el impuesto sobre el patrimonio y en el impuesto sobre sucesiones y donaciones",
	"Un impuesto de sociedades más sencillo y transparente",
	"Modificación de la imposición indirecta, en particular el IVA",
	"Establecimiento de una verdadera fiscalidad verde",
	"Coordinación de los impuestos medioambientales de las comunidades autónomas",
	"«Impuesto de solidaridad» a las entidades financieras privadas con carácter extraordinario",
	"Avance hacia el impuesto sobre transacciones financieras",
	"Acuerdo por la financiación territorial",
	"Mejora de la regulación del sistema financiero",
	"Eliminación del secreto bancario privilegiado de los paraisos fiscales",
	"Creación de una agencia europea de calificación independiente y pública",
	"Constitución de una potente y eficaz banca pública a partir de las entidades nacionalizadas Bankia y Banco Mare Nostrum",
	"Conversión de la Sareb en un instrumento de gestión de un parque público de vivienda en alquiler",
	"Derogación de la reforma del artículo 135 de la Constitución española",
	"Puesta en marcha de una auditoría de la deuda en sede parlamentaria",
	"Reestructuración de la deuda pública",
	"Reestructuración de la deuda hipotecaria de los hogares",
	"Limitación de los incentivos fiscales a la deuda empresarial",
	"Sanciones reales y efectivas a quienes incumplan la ley de morosidad",
	"Refuerzo del apoyo a la pequeña empresa entre las actividades del ICO y la futura banca pública",
	"Cuotas justas para los autónomos",
	"Incorporación de la voz de la economía social y de los autónomos en el diálogo social",
	"Estudio del desarrollo de la figura del autónomo de responsabilidad limitada",
	"Desarrollo de una verdadera Ley de Segunda Oportunidad, también en el terreno de las pymes y los autónomos",
	"Introducción del criterio del IVA de caja como universal y obligatorio",
	"Fomento de la economía social",
	"Potenciación de una economía del bien común",
	"Apoyo a la economía colaborativa",
	"Fomento del emprendimiento en sectores innovadores",
	"Cuotas pesqueras justas y responsables",
	"Trabajo agrario estable",
	"Asignación de 25 000 millones de euros anuales para un Plan de Bienestar Social y Modernización Económica que incluirá una renta garantizada, la mejora salarial y la reversión de los recortes sufridos desde 2010",
	"Aumento de entre 30 000 y 40 000 millones de euros de los ingresos sobre el PIB",
	"Modificación del calendario actual de reducción del déficit público",
	"Abandono de la política de devaluación salarial como vía para promover una mejora de la competitividad",
	"Impulso de una reforma sustancial del Pacto de Estabilidad y Crecimiento y del Pacto Fiscal",
	"Garantía de un nivel adecuado de inversión pública",
	"Promoción de la reforma de los estatutos del Banco Central Europeo",
	"Impulso de una reforma de las instituciones europeas que democratice la toma de decisiones políticas y económicas en la eurozona",
	"Convocatoria de una conferencia europea de deuda para discutir la reestructuración coordinada de las deudas públicas en el marco de la zona euro",
	"Adopción de forma inmediata de un plan de choque para erradicar la pobreza y la exclusión infantil en todo el territorio europeo",
	"Desarrollo de un seguro de desempleo común que complemente los sistemas nacionales y que, en caso de crisis, actúe de estabilizador automático",
	"Creación de un «Eurogrupo Social»",
	"Prioridad del derecho al trabajo y de la creación de empleo",
	"Incremento gradual del salario mínimo interprofesional hasta llegar a 14 pagas de 800 euros al mes en enero de 2018",
	"Pleno cumplimiento de la normativa laboral",
	"Reequilibrio de la negociación colectiva",
	"Nuevo marco laboral",
	"Impulso de una regulación de las horas extraordinarias para evitar que se conviertan en un instrumento de distribución irregular de la jornada",
	"Reforma del despido",
	"Impulso de los mecanismos de flexibilidad interna en las empresas",
	"Hacia la igualdad de género en el mercado de trabajo: reforma del sistema de permisos por nacimiento o adopción",
	"Incremento de la participación de los trabajadores en la gestión de empresas",
	"Reforma o regularización de las relaciones de trabajo paralaborales",
	"Renta Garantizada",
	"Programa de Renta Complementaria",
	"Medidas complementarias para atender situaciones de urgencia social",
	"Reversión de los recortes en la financiación de la sanidad, la educación y el cuidado de las personas, de forma que en marzo de 2018 se recuperen los niveles anteriores a la crisis",
	"Universalización del derecho a que los servicios públicos de atención a la dependencia proporcionen una autonomía funcional plena",
	"Eliminación de todos los incentivos al empleo a tiempo parcial y avance hacia la progresiva implantación de una jornada laboral máxima de 35 horas semanales, con cómputo semanal",
	"Lucha contra la brecha salarial de género",
	"Jubilación a los 65 años y lucha contra la pérdida del poder adquisitivo",
	"Compromiso de garantizar la sostenibilidad del sistema de pensiones con la introducción progresiva de la financiación por vía impositiva",
	"Revisión y progresiva supresión de los regímenes especiales de cotización para nuevas afiliaciones",
	"Fomento de la previsión colectiva de carácter público frente a la individual",
	"Aumento de las pensiones no contributivas",
	"Eliminación del tope máximo a las cotizaciones de los salarios más altos",
	"Acceso universal a la tarjeta sanitaria",
	"Incremento del presupuesto público en sanidad en 8800 millones de euros",
	"Ampliación de la cartera de medicamentos financiados",
	"Prescripción responsable de medicamentos: un modelo que dispensa dosis y no cajas",
	"Universalización de las recetas electrónicas: ahorro en el tiempo de los profesionales y en el dinero de todos",
	"Alimentos sin contaminantes: prohibición del uso de bisfenol A",
	"Ley para la Libre Disposición de la Propia Vida",
	"Medicamentos: I+D+i y transparencia",
	"Las TIC al servicio de la salud: creación de una plataforma digital estatal de acceso a las historias clínicas",
	"La salud: un enfoque transversal a todas las políticas públicas",
	"I+D+i: potenciación de las líneas de investigación y actuación sobre género y salud",
	"RedETS: evaluación de los programas que aportan más salud a la gente",
	"Un régimen único para todos: la Seguridad Social",
	"Ley de Transparencia del Sistema Sanitario",
	"Aprobación de una «Ley Celíaca»",
	"Fin de los desahucios y despenalización del uso de viviendas vacías y abandonadas",
	"Derecho a la dación en pago",
	"Acceso garantizado a los suministros básicos",
	"Alquiler estable y asequible",
	"Garantías de defensa y de prueba en el procedimiento de la ejecución hipotecaria",
	"Reforma de la Ley 18 / 2007, de 28 de diciembre, del derecho a la vivienda",
	"Garantía constitucional de los derechos sociales",
	"13 700 millones de euros para la educación pública: plazas escolares gratuitas y de proximidad para todos los niños y todas las niñas",
	"Una nueva Ley de Educación, que nazca del debate y la participación de toda la comunidad educativa",
	"Plan Nacional de Educación Inclusiva",
	"Derecho a una educación vehiculada en las lenguas cooficiales",
	"Plan de Aprendizaje Integrado de Lenguas Extranjeras",
	"Normalización de las metodologías participativas",
	"Generalización de los centros integrados de enseñanzas de régimen general y especial de música y danza",
	"Inteligencia emocional",
	"Dotación de mayores competencias a los consejos escolares",
	"Nuevo sistema de acceso a la función pública docente",
	"Disminución de la ratio de alumnado por aula",
	"Plan de Apoyo a Centros y Equipamientos Escolares",
	"Educación infantil de 0 a 6 años universal y gratuita",
	"Formación Profesional realmente gratuita en todos los niveles",
	"Nueva Ley de Universidades",
	"Tasas universitarias accesibles para todas y todos",
	"Educación a lo largo de toda la vida: educación para adultos",
	"Reforma universitaria participativa",
	"Consorcio universitario para la gestión de gastos",
	"Fin de la precariedad del profesorado universitario",
	"Reforma de la Agencia Nacional de Evaluación de la Calidad y Acreditación (ANECA)",
	"Por una infancia sin deberes",
	"Medidas urgentes contra la pobreza infantil y la exclusión social",
	"Ley de Protección Integral contra la Violencia hacia la Infancia y la Adolescencia",
	"Niñas, niños y adolescentes: prioridad de las instituciones",
	"La receta deportiva: más polideportivo y menos ambulatorio",
	"Fondo Social del Deporte: el deporte de todos",
	"Plan de apoyo a deportistas de alto nivel",
	"Ley de Regulación de las Profesiones del Deporte",
	"Más deporte en las escuelas: tres horas de Educación Física semanales e incorporación de la asignatura de Educación Física al currículo de segundo de bachillerato",
	"Ley de Mecenazgo y Patrocinio Deportivo",
	"Plan Estratégico para el Deporte Adaptado",
	"Creación del Observatorio de la Integridad del Deporte contra el Fraude, Amaños de Partidos y Resultados Deportivos",
	"Creación de una Cartera Estatal de Servicios Sociales Garantizados",
	"Un centro de servicios sociales por cada veinte mil habitantes",
	"Dotación estatal de 85 millones de euros para el Plan Concertado de Prestaciones Básicas de Servicios Sociales en corporaciones municipales",
	"Adecuación de los recursos humanos y materiales de los servicios sociales públicos a la demanda real existente",
	"Creación del Instituto de Innovación e Investigación en Servicios Sociales",
	"Creación de un fondo estatal para la accesibilidad universal",
	"Atención / Intervención Temprana pública, gratuita, universal y de calidad",
	"Ley de Autonomía y Dignidad de las personas en situación de dependencia, sus asistentes y sus familias",
	"Plan de choque por la dignidad de las personas en situación de dependencia y sus familias",
	"Principios y valores de la Convención Internacional sobre los Derechos de las Personas con Discapacidad",
	"Ampliación del derecho al voto a las personas con diversidad funcional",
	"Ley de Inclusión Laboral de Personas con Diversidad Funcional",
	"Foro Ciudadano Permanente sobre Dependencia y Diversidad Funcional",
	"Financiación de las organizaciones del tercer sector dedicadas a la atención de personas con diversidad funcional o dependencia",
	"Rehabilitación y fisioterapia continuadas gratuitas para las personas en situación de dependencia o diversidad funcional",
	"Aumento y agilización de las prestaciones por material ortoprotésico",
	"Reconocimiento constitucional de las lenguas de signos españolas como lenguas cooficiales",
	"Implementación de la perspectiva de género en las instituciones de la Administración General del Estado para eliminar la discriminación y hacer efectiva la igualdad entre hombres y mujeres",
	"Mujeres en las Fuerzas Armadas y en los Cuerpos y Fuerzas de Seguridad del Estado",
	"Frente a las violencias machistas, la independencia de las mujeres",
	"Ley Contra la Discriminación por Motivos de Identidad de Género y Orientación Sexual",
	"Ley Integral contra la Trata de Personas",
	"Elaboración de la nueva Ley de Identidad de Género",
	"Plan Estratégico para la Conciliación de la Vida Laboral y Familiar",
	"Protección a las familias monoparentales",
	"Plan de apoyo destinado a las madres y a los padres jóvenes",
	"Reconocimiento de todas las realidades familiares",
	"Derecho a la maternidad libre y decidida",
	"Respeto a la determinación sobre el propio embarazo, parto y posparto",
	"Plan de lucha contra el VIH: información, prevención y atención",
	"Garantía habitacional para las víctimas de violencia machista",
	"Proteger el derecho a decidir de todas las mujeres",
	"Ratificación urgente del Convenio 189 de la Organización Internacional del Trabajo",
	"Familias monomarentales: por una maternidad independiente y segura",
	"Ministerio de Cultura y Comunicación",
	"Pacto por la Cultura y leyes específicas para el sector cultural",
	"Ley de Enseñanzas Artísticas Superiores",
	"Reforma de la Ley General de la Comunicación Audiovisual",
	"Asamblea de Profesionales de la Cultura y Observatorio Ciudadano de la Cultura",
	"Medidas para el ejercicio responsable y eficaz de la Administración Cultural Pública",
	"Dirección General de la Cultura Digital y Plataforma Pública de Cultura Abierta",
	"IVA cultural reducido",
	"Nueva Ley de Mecenazgo y Patrocinio y Fondo Social de la Cultura",
	"Estatuto del Artista y del Profesional de la Cultura",
	"Estatuto de la Información",
	"Nueva Ley de Propiedad Intelectual",
	"Plan Operativo de Fomento de la Difusión y el Acceso a la Cultura Digital",
	"Plan Operativo de Acceso y Disfrute de la Cultura",
	"Plan Operativo para una Ciudadanía Lectora",
	"Escuela de Espectadores",
	"Campaña para una Audiencia Activa",
	"Plan Operativo de Fomento de la Diversidad Cultural",
	"Plan Operativo de Cultura por la Igualdad e Igualdad en la Cultura",
	"Plan Operativo de Inclusión Social en Materia Cultural",
	"Plan Operativo de Internacionalización de la Cultura Producida en España",
	"Red de Destinos Patrimoniales",
	"Revocatorios por incumplimiento del programa electoral",
	"Revocación de cargos públicos, Iniciativa Legislativa Popular, Iniciativa de Veto Popular e Iniciativa de Procesos Deliberativos Populares: la democracia",
	"Reglamentos parlamentarios para el debate democrático de todas y de todos",
	"Igualdad política: reforma del sistema electoral",
	"Nuevo modelo territorial basado en cinco ejes conceptuales",
	"Obligación legal de presentarse a primarias por parte de todos aquellos candidatos a presidir órganos ejecutivos de los partidos políticos",
	"Derogación del voto rogado y creación de una ley electoral que facilite el ejercicio del derecho al sufragio de los españoles en el extranjero",
	"Despolitización del Tribunal Constitucional",
	"Eliminación de privilegios de los cargos electos",
	"Ley de Profesionalización de la Administración Pública",
	"Reducción del número de altos cargos",
	"Recuperación de los derechos laborales en el sector público",
	"Ampliación de la Ley de Transparencia",
	"Regulación de las incompatibilidades en los cargos públicos",
	"Ley de Paredes de Cristal",
	"Reformulación de la Ley de Contratos del Sector Público",
	"Seguimiento de la ejecución presupuestaria",
	"Observatorio Ciudadano de Evaluación de Políticas Públicas y Rendición de Cuentas",
	"Contratos administrativos abiertos y accesibles",
	"Plan Nacional contra la Corrupción y para la Transparencia Institucional",
	"Policía judicial y peritos para su adscripción funcional a los juzgados",
	"Introducción de la figura delictiva de enriquecimiento injusto o ilícito",
	"Nueva Ley de Financiación de Partidos Políticos",
	"Creación del Departamento de Recuperación de Activos",
	"Redefinición del delito fiscal",
	"Fortalecimiento de los sistemas de evaluación legislativa en materia de corrupción y política criminal",
	"Participación ciudadana en la gestión pública",
	"Justicia gratuita real",
	"Elección directa del Consejo General del Poder Judicial",
	"Auditoría pública del sistema judicial",
	"Reforma integral de la Fiscalía",
	"Eliminación de privilegios procesales",
	"Derogación de la Ley Orgánica de modificación de la Ley de Enjuiciamiento Criminal",
	"Multas y sanciones administrativas proporcionales a la renta de las personas",
	"Derogación de la ley mordaza",
	"Creación de la Oficina de Derechos Humanos del Gobierno",
	"Memoria, verdad y justicia: pilares de la cultura de los derechos humanos",
	"Creación de la Agencia Estatal para la Protección de los Consumidores",
	"Derecho de indemnización del consumidor víctima de un abuso",
	"Despenalización del cannabis",
	"Software libre para una Administración abierta, segura y accesible",
	"Simplificación de los procedimientos administrativos",
	"Gestión directa en la Administración Pública y optimización del desempeño de los profesionales",
	"Auditorías regulares de los organismos públicos",
	"Homologación de las jornadas de trabajo de las Fuerzas Armadas a las del resto de la Administración Pública",
	"Redefinición de la carrera militar de todos los militares profesionales",
	"Militares: ciudadanos y trabajadores",
	"Transparencia y control democrático para Defensa",
	"Personal civil a cargo de las tareas administrativas en las Fuerzas Armadas",
	"Libertad de sindicación para los miembros de la Guardia Civil",
	"Mejora de la coordinación entre la Guardia Civil y la Policía Nacional",
	"Nuevo sistema de ascenso en las Fuerzas de Seguridad del Estado",
	"Derecho a decidir",
	"Reforma del Senado",
	"Revisión del modelo de financiación",
	"Paralización de la ley Montoro",
	"Plan de Uso Social de la Tierra",
	"Nueva Ley de Aguas",
	"Quien contamina paga",
	"Protección del medio marino y su entorno",
	"Ciudades sostenibles",
	"Fomento de la economía circular: Objetivo Residuo CERO",
	"Rescate ecológico: salvar nuestra biodiversidad",
	"Lucha contra el cambio climático",
	"Estrategia Integral de Participación y Educación Ambiental",
	"Vicepresidencia de Sostenibilidad",
	"El agua: un derecho humano",
	"Un medio ambiente seguro como derecho fundamental",
	"Anulación del Concordato",
	"Nueva Ley de Libertad de Conciencia",
	"Un mundo rural vivo y sostenible",
	"Cuidar nuestros montes",
	"Garantía de acceso al transporte público",
	"Vertebrar el territorio e impulsar la economía desde el ferrocarril",
	"Objetivo CERO en accidentes de tráfico",
	"Nueva Ley de Usos del Suelo",
	"Nueva Ley de Protección del Paisaje",
	"Plan para la Protección Efectiva del Litoral",
	"Ley de Bienestar Animal",
	"Cobertura sanitaria universal",
	"Oficina de la Emigración",
	"Normativa para la enseñanza de la lengua y la cultura españolas en el extranjero",
	"Desarrollo de medidas de garantía de pensiones dignas para los españoles emigrantes y retornados",
	"Establecimiento de mecanismos y organismos que posibiliten el retorno de los emigrantes españoles",
	"Derecho a voto y a la participación política de la población extranjera residente en nuestro país",
	"Eliminación del test de nacionalidad y reducciones en los plazos para obtener la nacionalidad",
	"Creación de la Secretaría de Estado de Políticas Migratorias",
	"Vías legales y seguras de entrada en España y flexibilización de los procesos de reagrupación familiar",
	"«Ley 14» para la igualdad de trato y para el fomento de la convivencia",
	"Cierre de los Centros de Internamiento de Extranjeros",
	"Garantía del derecho de asilo: vías legales de acceso, sistema común de asilo y programas dignos de reasentamiento",
	"Restablecimiento de la legalidad de los pasos fronterizos: respeto a los derechos humanos en la frontera sur",
	"Aprobación de un marco jurídico internacional para la reestructuración de la deuda soberana",
	"Prohibición de los productos financieros altamente especulativos",
	"Reforma de los sistemas de votación del G-20 y del Fondo Monetario Internacional",
	"Contra la evasión fiscal: «tasa Tobin» e impuesto global sobre la riqueza",
	"Establecimiento de una lista negra de paraísos fiscales",
	"Oposición al TTIP",
	"Hacia la abolición del derecho de veto en el Consejo de Seguridad de la ONU",
	"Impulso de la elección de una mujer como próxima secretaria general de la ONU",
	"Sometimiento a consulta ciudadana de la participación de las Fuerzas Armadas en operaciones militares internacionales",
	"Auditoría y revisión del convenio con Estados Unidos sobre la base militar permanente en Morón",
	"Mayor autonomía de España y Europa en la OTAN",
	"Derechos para las migraciones de ida y vuelta entre España y América Latina",
	"Compromiso con la libre determinación del Sáhara Occidental y concesión de la nacionalidad española a la población saharaui residente en España",
	"Reconocimiento del Estado palestino",
	"Nuevo Plan África",
	"Cooperación científica y cultural con Estados Unidos para evitar la fuga de cerebros",
	"Reducción de gastos suntuarios del servicio exterior y más atención a emigrantes españoles",
	"Transformación de la Marca España y del Instituto Cervantes para que sean reflejo de la diversidad y plurinacionalidad de nuestro país",
	"Aprobación de un Pacto por la Justicia Global y de una Ley de Solidaridad y Cooperación Internacional",
	"Aumento del presupuesto destinado a la Ayuda Oficial al Desarrollo",
	"Creación del Ministerio de Igualdad y Solidaridad",
	"Liberalización de la AP-4 (Sevilla-Jerez)",
	"Inmatriculaciones de la Iglesia católica",
	"Regulación de aprovechamientos hidráulicos de las subcuencas de los ríos Genil, Fardes y Guadiana Menor",
	"Descontaminación de terrenos anteriormente utilizados por la industria",
	"Mejora y creación de nuevos tramos en la red de carreteras",
	"Construcción de una segunda presa en el pantano de la Concepción",
	"Mejora de la red ferroviaria para la vertebración de Andalucía",
	"Plan integral de protección del olivar y su industria",
	"Plan de mejora y redimensionamiento de la empresa pública incineradora REMESA",
	"Reapertura de la línea ferroviaria Canfranc-Olorón en el horizonte 2020",
	"Paralización de las obras de recrecimiento del pantano de Yesa",
	"Mejora del corredor ferroviario Cantábrico-Mediterráneo",
	"Fondos mineros para el desarrollo de Asturias",
	"Plan de infraestructuras",
	"Impulso de un régimen específico balear basado en el equilibrio económico y solidario entre los distintos territorios del Estado español",
	"Declaración de interés público de las conexiones interislas y peninsulares para Islas Baleares y las islas Canarias",
	"Reconocimiento de Canarias como Región Ultraperiférica (RUP) en la Constitución española",
	"Fomento de las actuaciones derivadas de la reserva de inversiones para Canarias",
	"Cumplimiento de los principales objetivos y medidas de los Programas de Opciones Específicas por la Lejanía y la Insularidad (POSEI) para garantizar la dotación presupuestaria",
	"No al fracking en Cantabria",
	"Plan de reactivación económica para las comarcas del Besaya y de Reinosa",
	"Paralización completa del almacén temporal centralizado de Villar de Cañas",
	"Plataforma logística intermodal y tren de mercancías para Toledo",
	"Propuesta de anteproyecto de ley para la defensa de la autonomía local y el reconocimiento de las comarcas",
	"Ferrocarril para Castilla y León",
	"Ampliar y mejorar el sistema de Cercanías (Rodalies) de la región metropolitana de Barcelona",
	"Cumplimiento del Estatuto de Autonomía de Cataluña en relación con las inversiones en infraestructuras",
	"Mejora de la red ferroviaria en las comarcas de montaña",
	"Autovía Lleida-Pirineus",
	"Cooperación transfronteriza",
	"Paralización de la A-57 para salvar los montes gallegos",
	"Saneamiento de la ría del Burgo",
	"Recuperación de la ría de Pontevedra para la ciudadanía",
	"Dotar de más agua (y de mejor calidad) al río Tajo a su paso por Aranjuez",
	"Resolución del proyecto de construcción de la línea de tren de Cercanías Móstoles-Navalcarnero",
	"Eliminación, soterramiento o traslado de las dos líneas de alta tensión que actualmente atraviesan de norte a sur el municipio de Arroyomolinos, por encima de viviendas, zonas verdes, áreas infantiles y zonas deportivas",
	"Cumplimiento de las medidas de conservación y restauración de la cuenca hidrográfica del río Guadarrama",
	"Recuperación del proyecto para ampliar la línea C4 de tren de Cercanías hasta los municipios de Torrejón de la Calzada y Torrejón de Velasco",
	"Revisión del proyecto de soterramiento de las vías del tren en el sur de Madrid",
	"Mejora de la red ferroviaria de la Región de Murcia",
	"Plan de defensa del litoral murciano",
	"Desmantelamiento del polígono de tiro de las Bardenas Reales",
	"Paralización de las obras del tren de alta velocidad",
	"Regeneración del tejido productivo de las zonas industriales",
	"Apertura de un proceso de diálogo para la ampliación de competencias transferidas al País Vasco",
	"Plan urgente de reindustrialización para La Rioja",
	"Eliminación del requisito de no tener deudas con las administraciones públicas para poder acceder a los fondos de los servicios sociales",
	"Plan integral para mejorar las infraestructuras de transporte y comunicaciones",
	"Aumento de la financiación estatal en apoyo del emprendimiento y las pymes",
	"Apoyo a la agricultura, la ganadería y la pesca",
	"Preservación de los espacios naturales",
	"Turismo sostenible",
	"Inembargabilidad de la primera y única vivienda",
	"Eliminación de las cláusulas abusivas",
	"Observatorio del Derecho a la Vivienda",
	"Justicia independiente para los militares",
	"Una sanidad de gestión pública y un derecho garantizado para todas las personas en igualdad, con independencia del lugar donde se resida"
]

var propuestasCiudadanos = [
	"Nueva sección de derechos sociales en la Constitución",
	"Políticos sin privilegios",
	"Despolitización de la Justicia",
	"Organización territorial del Estado: leal, eficaz, ciudadana",
	"Una cartera de servicios común en toda España.",
	"Una administración más eficiente",
	"Una nueva ley electoral",
	"Europa y más Europa",
	"Reconciliación entre los españoles",
	"Contrato estable de igualdad de oportunidades",
	"Complemento Salarial Anual Garantizado",
	"Una Reforma fiscal a favor de la clase media",
	"Impulso para los autónomos",
	"Programa contra el Paro de larga duración",
	"Lucha contra el fraude",
	"Gratuidad de la enseñanza",
	"Independencia de los centros",
	"Un modelo plurilingüe en la escuela pública",
	"Un MIR docente: concursos de provisión y formación del profesorado",
	"Reforma universitaria",
	"Promover la cultura científica en España",
	"Aumento de la inversión en I+D",
	"Desarrollo de Centros de Investigación de Excelencia",
	"Fortalecimiento del Sistema Nacional de Salud",
	"Regulación de la muerte digna",
	"Regulación de la maternidad subrogada",
	"Derecho a la Vivienda",
	"Pensiones",
	"Política migratoria común europea",
	"Dependencia",
	"Un Pacto Nacional por la Racionalización de Horarios y la Conciliación Laboral.",
	"Nuevo esquema de baja por maternidad y paternidad",
	"Promoción del servicios de educación inicial",
	"Igualdad y lucha frente a la violencia contra las mujeres y la violencia intrafamiliar",
	"Protección a los denunciantes de casos de corrupción",
	"Imputados fuera de las listas electorales",
	"Los partidos responderán por la corrupción de sus cargos públicos",
	"Supresión de la cláusula suelo",
	"Mejorar el funcionamiento de los partidos políticos",
	"Más recursos materiales y humanos para la Justicia",
	"Fomento de la cultura desde la escuela",
	"Fomentar la industria audiovisual",
	"Consolidar la protección de la Propiedad Intelectual",
	"Protección del patrimonio",
	"Fortalecimiento del Instituto Cervantes",
	"Protección a los creadores",
	"Nueva ley de mecenazgo",
	"Una RTVE independiente y de calidad",
	"Promoción del Deporte para la salud ",
	"Apoyo al atleta de alta competencia",
	"Una carrera diplomática más profesional",
	"Consolidar la financiación para Cooperación y Desarrollo",
	"Participación política de los españoles en el exterior",
	"Política de Defensa Europea",
	"Política Fiscal Europea",
	"Mercado Laboral Europeo",
	"Gran Pacto Nacional por las Infraestructuras",
	"Infraestructuras prioritarias",
	"Vivienda Social",
	"Mercado Inmobiliario",
	"Despolitizar las empresas públicas",
	"Más seguridad para las infraestructuras",
	"Nuevo modelo energético",
	"Protección del autoconsumo",
	"Bajar los costes eléctricos a Pymes y familias",
	"Nueva Secretaría de Estado de Medio Ambiente y Energía",
	"Nueva Ley de Cambio Climático",
	"Apoyo a la Economía Circular",
	"Responsabilidad subsidiaria de empresas contaminantes",
	"Aumentar la protección a los animales",
	"Refuerzo de la lucha antiterrorista",
	"Nuevo Estatuto de la Víctima",
	"Reforma del sistema policial",
	"Más eficiente despliegue policial en el territorio",
	"Más eficiente coordinación policial",
	"Mejores condiciones laborales para los funcionarios",
	"Nueva Ley de la Defensa",
	"Nueva Estrategia de Ciberseguridad",
	"Fortalecimiento de la autoridad del JEMAD",
	"Nueva Ley de la Carrera Militar",
	"Apoyo a las familias de los miembros de las FFAA"
]